### ISSUE TITLE
systemd script can start lanterna too early, no IP addresses -> fail

### ISSUE THREAD

**Issue by marco-m-pix4d** [marco-m/lanterna#1]
```
Jul 03 14:04:23 systemd[1]: Starting lanterna IP address publisher...
Jul 03 14:04:23 lanterna[471]: lanterna: error: run: could not find any IP address ([])
Jul 03 14:04:23 systemd[1]: lanterna.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 14:04:23 systemd[1]: lanterna.service: Failed with result 'exit-code'.
Jul 03 14:04:23 systemd[1]: Failed to start lanterna IP address publisher.
```

- At the very minimum, it should report the error to the chat.
- Even better, it should be a service and send a message daily...

**Comment by marco-m-pix4d** [comment]
- fix: run and collect: if no IP addresses found, send a warning! e4179ca0a42539c4e47ed59023ebeabfac87f756

**Comment by marco-m** [comment]
- fix: run and collect: if no IP addresses found, send a warning! e4179ca0a
- transform lanterna to a real service, sending a message periodically 10f4df2
